-- No source text available
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'users', 'users', 2, 'CREATE TABLE `users` (`userTag` VARCHAR(255), `userId` VARCHAR(255) PRIMARY KEY, `balance` INTEGER DEFAULT 0, `xp` INTEGER NOT NULL DEFAULT 0, `level` INTEGER DEFAULT 0, `lastMessageDate` VARCHAR(255) DEFAULT 0, `isBanned` INTEGER DEFAULT 0, `dailyTaken` VARCHAR(255), `dailyStreak` INTEGER DEFAULT 0)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_users_1', 'users', 3, null);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'servers', 'servers', 4, 'CREATE TABLE `servers` (`serverName` VARCHAR(255), `serverId` VARCHAR(255) PRIMARY KEY)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_servers_1', 'servers', 5, null);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'ServerUsers', 'ServerUsers', 6, 'CREATE TABLE `ServerUsers` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `guildId` VARCHAR(255), `userId` VARCHAR(255), `xp` INTEGER NOT NULL DEFAULT 0, `lastMessageDate` VARCHAR(255), `isMuted` INTEGER)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'sqlite_sequence', 'sqlite_sequence', 7, 'CREATE TABLE sqlite_sequence(name,seq)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'Timers', 'Timers', 8, 'CREATE TABLE `Timers` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `guildId` VARCHAR(255), `userId` VARCHAR(255), `moderatorId` VARCHAR(255), `type` VARCHAR(255), `expiration` VARCHAR(255), reason VARCHAR(1000))');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'Warnings', 'Warnings', 9, 'CREATE TABLE `Warnings` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `casenr` INTEGER, `guildId` VARCHAR(255), `userId` VARCHAR(255), `moderatorId` VARCHAR(255), `reason` VARCHAR(255))');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'serverSettings', 'serverSettings', 10, 'CREATE TABLE `serverSettings` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `serverId` VARCHAR(255), `prefix` VARCHAR(255), `muteRoleId` VARCHAR(255), `modlogChannel` VARCHAR(255), `joinLeaveLogChannel` VARCHAR(255), `memberLogChannel` VARCHAR(255), `serverLogChannel` VARCHAR(255), `messageLogChannel` VARCHAR(255), `voiceLogChannel` VARCHAR(255), `levelUpMessage` VARCHAR(255), `levelUpRoleMessage` VARCHAR(255), `noXpRole` VARCHAR(255), joinMessage VARCHAR(1000), joinMessageChannel VARCHAR(255), leaveMessage VARCHAR(1000), leaveMessageChannel VARCHAR(255))');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'rewards', 'rewards', 32, 'CREATE TABLE `rewards` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `serverId` VARCHAR(255), `xp` INTEGER, `roleId` VARCHAR(255))');